### ISSUE TITLE
i2s dma  hao pop

### ISSUE THREAD

**Issue by xinshuwei** [Analog-Devices-MSDK/msdk#290]
i have  MAX78000 FTHR_RevA board  .I want set up max9867 codec. I learn I2S config with example.
Codec is working,i found use 

MXC_DMA_ReleaseChannel(0);
MXC_I2S_TXDMAConfig() 
This code once play is ok,but when i send a  lot of samples with “SDHC fread“  wav files, release dma ch and TXDMAConfig(), Codec play audio have pop, I have capture this audio wav with audtion（set send bu'ffer size is 1600 ,16bit two ch out,400 samples have pop）
![93114dbfe8d524da031f5874a1c861f](https://user-images.githubusercontent.com/27468495/197238464-e4b1daa7-ceaf-4522-9132-16349680f138.jpg)

How can i setup is codec with FTHR_RevA I2S ,playback a long file is not have pop? Can help me?

**Comment by Jake-Carter** [comment]
@xinshuwei It's a difficult issue to debug remotely.

As Jesse mentioned a double-buffered approach with DMA is recommended.

I would also recommend using `f_stream` instead of `f_read`.  From the [f_read documentation](http://elm-chan.org/fsw/ff/doc/read.html): **"If the file needs to be read fast, it should be read in large chunk as possible."**  `f_read` is slow.  See [f_forward](http://elm-chan.org/fsw/ff/doc/forward.html) for documentation and [out_stream](https://github.com/Analog-Devices-MSDK/msdk/blob/bc90c7d6c4a2f54866a67d497cb8d8753013e4e2/Examples/MAX78000/ImgCapture/src/console/console.c#L245) for an example where I implemented the data streaming function to stream to UART.

Additionally, have you verified that the sine lookup table you're sending from is _perfectly continuous_?  I would recommend starting and ending blocks of audio data at the [Zero-Crossing](https://en.wikipedia.org/wiki/Zero_crossing) for a sine wave.

**Comment by xinshuwei** [comment]
[Desktop.zip](https://github.com/Analog-Devices-MSDK/msdk/files/10241572/Desktop.zip)
@Jake-Carter  Thanks your reply.
1.I had upload  my file, please check.  
2. "f_stream" instead of f_read   i will try it, thks.
