### ISSUE TITLE
No GPIO IRQ handlers defined for MAX32690 EvKit_V1

### ISSUE THREAD

**Issue by Vitorbnc** [Analog-Devices-MSDK/msdk#705]
The provided GPIO example for EvKitV1 does not work as expected, execution stops as soon as the gpio interrupt is triggered.

The GPIO IRQ handlers are declared in  startup_max32690.s:

    def_irq_handler GPIO0_IRQHandler             /* 0x28  0x00A0  40: GPIO0 */
    def_irq_handler GPIO1_IRQHandler             /* 0x29  0x00A4  41: GPIO1 */
    def_irq_handler GPIO2_IRQHandler             /* 0x2A  0x00A8  42: GPIO2 */

However, there is no IRQ handler function that matches these names in board.c for the EvKitV1, so the common handler is never called.

The definition was provided for other evaluation kits:

```
__weak void GPIO2_IRQHandler(void)
{ 
MXC_GPIO_Handler(MXC_GPIO_GET_IDX(MXC_GPIO2)); 
} 
```

**Comment by Jake-Carter** [comment]
Thanks @Vitorbnc, we'll get this defined in the board file.

It looks like the GPIO example needs a refresh in general.

It's attempting to set up _both_ an ISR and a callback function but doesn't do either correctly.  Since the GPIO for the pushbutton is parameterized the example is overly reliant on weak handlers being defined in the board files.

I would recommend defining the ISR locally if you wanted to keep using the callbacks.

```diff
 /***** Functions *****/
-void gpio_isr(void *cbdata)
-{
-    MXC_Delay(MXC_DELAY_MSEC(100));
-    uint32_t flags = MXC_GPIO_GetFlags(MXC_GPIO_PORT_IN);
-    MXC_GPIO_ClearFlags(MXC_GPIO_PORT_IN, flags);
-
+void sw2_callback(void *cbdata) {
     mxc_gpio_cfg_t *cfg = cbdata;
     MXC_GPIO_OutToggle(cfg->port, cfg->mask);
 }

+void gpio_isr(void)
+{
+    MXC_Delay(MXC_DELAY_MSEC(100)); // Debounce
+    MXC_GPIO_Handler(MXC_GPIO_GET_IDX(MXC_GPIO_PORT_IN));
+}
+
 int main(void)
 {
     mxc_gpio_cfg_t gpio_out;
@@ -111,10 +112,11 @@ int main(void)
     gpio_interrupt.func = MXC_GPIO_FUNC_IN;
     gpio_interrupt.vssel = MXC_GPIO_VSSEL_VDDIOH;
     MXC_GPIO_Config(&gpio_interrupt);
-    MXC_GPIO_RegisterCallback(&gpio_interrupt, gpio_isr, &gpio_interrupt_status);
+    MXC_GPIO_RegisterCallback(&gpio_interrupt, sw2_callback, &gpio_interrupt_status);
     MXC_GPIO_IntConfig(&gpio_interrupt, MXC_GPIO_INT_FALLING);
     MXC_GPIO_EnableInt(gpio_interrupt.port, gpio_interrupt.mask);
     NVIC_EnableIRQ(MXC_GPIO_GET_IRQ(MXC_GPIO_GET_IDX(MXC_GPIO_PORT_IN)));
+    MXC_NVIC_SetVector(MXC_GPIO_GET_IRQ(MXC_GPIO_GET_IDX(MXC_GPIO_PORT_IN)), gpio_isr);

     /* Setup output pin. */
     gpio_out.port = MXC_GPIO_PORT_OUT;
```

... but the latency and memory overhead (#269) for the callbacks is pretty significant.  The lowest latency option is to just use the ISR directly.
