### ISSUE TITLE
MAX32675: I²C instance 1 does not exist but is defined in I2C_me15.c

### ISSUE THREAD

**Issue by oledreessen** [Analog-Devices-MSDK/msdk#738]
there're some mentions of i2c**1** the i2c driver (file i2c_me15.c line of the max32675 which does not exist:

function MXC_I2C_ReadRXFIFODMA in line 210
function MXC_I2C_WriteTXFIFODMA in line 245

the above list is not complete

**Comment by Jacob-Scheiffler** [comment]
Ole, this bug was recently resolved in #693. The changes are available in the main branch and will be included in the next SDK release coming soon.

We still allow MXC_I2C1 to be passed as an argument to most MAX32675 I2C functions because it's technically a valid option (the MAX32675 has an I2C1 instance, it's just not pinned out) and wanted to reduce the overhead and clutter of checking in every function. That said we still return an E_NO_DEVICE error from the MAX32675 I2C initialization function to provide some indication that this selection won't work for the application.
